server:
  port: 8080
spring:
  application:
    name: plant_market
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PlantMarket?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  main:
    allow-circular-references: true
  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: google/gemma-3-27b-it:free
jwt:
  secret: IAmPacmanIsSoCoolAndIncrediblyVip2004
payos:
  client-id: "c8afd23e-d746-403b-a2ee-03e3b6a62348"
  api-key: "6da31a52-547d-489d-97a2-cbba0450ab5d"
  checksum-key: "03ed2aac3c7dfbbe1e3cf434b5d7f29217275036d0fbbfcc096aca33dcd9b044"